apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    namespace "com.symbol.udisample1"
    defaultConfig {
        applicationId "com.symbol.udisample1"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 6
        versionName "7.3.3"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compileOnly 'com.symbol:emdk:11.0.134'
}
