apply plugin: 'com.android.application'
android {
    compileSdkVersion 36
    namespace "com.symbol.barcodesample1"
    defaultConfig {
        applicationId "com.symbol.barcodesample1"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 12
        versionName "7.3.3"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compileOnly 'com.symbol:emdk:11.0.134'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
}
